---
# Source: cert-manager/templates/startupapicheck-serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: true
metadata:
  name: cert-manager-startupapicheck
  namespace: cert-manager
  annotations:
    helm.sh/hook: post-install
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
    helm.sh/hook-weight: "-5"
  labels:
    app: startupapicheck
    app.kubernetes.io/name: startupapicheck
    app.kubernetes.io/instance: cert-manager
    app.kubernetes.io/component: "startupapicheck"
    app.kubernetes.io/version: "v1.12.17"
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: cert-manager-v1.12.17
