---
# Source: n8n/charts/valkey/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: n8n-valkey
  namespace: "n8n"
  labels:
    app.kubernetes.io/instance: n8n
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: valkey
    app.kubernetes.io/version: 8.0.2
    helm.sh/chart: valkey-2.4.7
    app.kubernetes.io/part-of: valkey
type: Opaque
data:
  valkey-password: "Ulo4aDhPSkxKcw=="
